name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up helloEmad.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.9'

      - name: Install dependencies and test
        run: |
          npm install
          npm test

      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deployment commands on server
        run: |
          ssh -o StrictHostKeyChecking=no root@168.119.238.20 << EOF
            cd /Home/Emad-test
            git pull origin main
            npm install
            npm run build
          EOF
